### ISSUE TITLE
support library 26 に更新したら Fragment#setNextAnim で強制終了する

### ISSUE THREAD

**Issue by mag0716** [mag0716/Android#29]
## 再現手順

* Recent Apps から削除
* ロック画面の Notification からアプリ起動

## 環境

* support library 26.1.0
* Android 8

**Comment by mag0716** [comment]
- [ ] https://github.com/mag0716/android_periodic_execution が開発環境が同じなので再現するか確認する
- [ ] 再現する最小のサンプルを作成する

**Comment by mag0716** [comment]
```
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.Fragment.setNextAnim(int)' on a null object reference
                                                                  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:765)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                  at android.os.Handler.handleCallback(Handler.java:789)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by mag0716** [comment]
再現するアプリで利用しているメソッド

* add, remove
* attach, detach
* replace
* addToBackStack
* commit, commitAllowingStateLoss

**Comment by mag0716** [comment]
https://stackoverflow.com/questions/13393693/android-fragmentmanager-backstackrecord-run-throwing-nullpointerexception

**Comment by mag0716** [comment]
例外の原因は、FragmentTransaction#remove(null) を呼んでいたこと。
Android 8 だけで、起こるのは、ロック画面からの起動で、ライフサイクルが異なるから。
(onStart が 2回呼ばれている)

詳細を調査する。

**Comment by mag0716** [comment]
```
11-03 00:46:50.413 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onCreate(savedInstanceState=null)
11-03 00:46:50.571 5092-5092/com.github.mag0716.launchfromlockscreennotification W/Notification: Use of stream types is deprecated for operations other than volume control
11-03 00:46:50.571 5092-5092/com.github.mag0716.launchfromlockscreennotification W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
11-03 00:46:50.576 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onCreate [163ms]
11-03 00:46:50.580 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onStart()
11-03 00:46:50.580 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onStart [0ms]
11-03 00:46:50.586 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onResume()
11-03 00:46:50.588 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onResume [2ms]
11-03 00:46:50.611 5092-5114/com.github.mag0716.launchfromlockscreennotification D/OpenGLRenderer: HWUI GL Pipeline
11-03 00:46:50.622 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onPause()
11-03 00:46:50.622 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onPause [0ms]
11-03 00:46:50.826 5092-5114/com.github.mag0716.launchfromlockscreennotification I/OpenGLRenderer: Initialized EGL, version 1.4
11-03 00:46:50.827 5092-5114/com.github.mag0716.launchfromlockscreennotification D/OpenGLRenderer: Swap behavior 1
11-03 00:46:50.827 5092-5114/com.github.mag0716.launchfromlockscreennotification W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
11-03 00:46:50.827 5092-5114/com.github.mag0716.launchfromlockscreennotification D/OpenGLRenderer: Swap behavior 0
11-03 00:46:50.829 5092-5114/com.github.mag0716.launchfromlockscreennotification D/EGL_emulation: eglCreateContext: 0xa0a47040: maj 2 min 0 rcv 2
11-03 00:46:50.830 5092-5114/com.github.mag0716.launchfromlockscreennotification D/EGL_emulation: eglMakeCurrent: 0xa0a47040: ver 2 0 (tinfo 0xa09a1800)
                                                                                                  
                                                                                                  [ 11-03 00:46:50.838  5092: 5114 D/         ]
                                                                                                  SurfaceInterface::setAsyncMode: set async mode 1
11-03 00:46:50.839 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onStop()
11-03 00:46:50.840 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onStop [0ms]
11-03 00:46:50.883 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onStart()
11-03 00:46:50.883 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onStart [0ms]
11-03 00:46:50.883 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onResume()
11-03 00:46:50.886 5092-5092/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onResume [0ms]
11-03 00:46:50.907 5092-5114/com.github.mag0716.launchfromlockscreennotification D/EGL_emulation: eglMakeCurrent: 0xa0a47040: ver 2 0 (tinfo 0xa09a1800)
```

**Comment by mag0716** [comment]
ステータスバーからの起動

```
11-03 00:48:24.250 5202-5202/? V/MainActivity: ⇢ onCreate(savedInstanceState=null)
11-03 00:48:24.350 5202-5202/? W/Notification: Use of stream types is deprecated for operations other than volume control
11-03 00:48:24.350 5202-5202/? W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
11-03 00:48:24.354 5202-5202/? V/MainActivity: ⇠ onCreate [103ms]
11-03 00:48:24.356 5202-5202/? V/MainActivity: ⇢ onStart()
11-03 00:48:24.356 5202-5202/? V/MainActivity: ⇠ onStart [0ms]
11-03 00:48:24.359 5202-5202/? V/MainActivity: ⇢ onResume()
11-03 00:48:24.360 5202-5202/? V/MainActivity: ⇠ onResume [1ms]
```

**Comment by mag0716** [comment]
Android 8

```
11-05 20:54:11.715 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onCreate(savedInstanceState=null)
11-05 20:54:11.732 4110-4110/com.github.mag0716.launchfromlockscreennotification W/Notification: Use of stream types is deprecated for operations other than volume control
11-05 20:54:11.732 4110-4110/com.github.mag0716.launchfromlockscreennotification W/Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
11-05 20:54:11.734 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onCreate [19ms]
11-05 20:54:11.737 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onStart()
11-05 20:54:11.737 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onStart [0ms]
11-05 20:54:11.742 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onResume()
11-05 20:54:11.748 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onResume [5ms]
11-05 20:54:11.756 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onPause()
11-05 20:54:11.756 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onPause [0ms]
11-05 20:54:11.823 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onStop()
11-05 20:54:11.823 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onStop [0ms]
11-05 20:54:12.094 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onStart()
11-05 20:54:12.095 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onStart [0ms]
11-05 20:54:12.095 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇢ onResume()
11-05 20:54:12.095 4110-4110/com.github.mag0716.launchfromlockscreennotification V/MainActivity: ⇠ onResume [0ms]
11-05 20:54:12.140 4110-4133/com.github.mag0716.launchfromlockscreennotification D/EGL_emulation: eglMakeCurrent: 0xa0cc4360: ver 2 0 (tinfo 0xacc0b290)
```
